### ISSUE TITLE
Property "salt-byte-size" is used to set hashBytesize attribute instead of saltByteSize

### ISSUE THREAD

**Issue by llsilveira** [scheuchzer/secure-password-hash#1]
This piece of code is from PasswordHash.java, line 231 (method configure()): 

if (props.getProperty(PARAM_SALT_BYTE_SIZE) != null) {
    setHashByteSize(Integer.parseInt(props
            .getProperty(PARAM_SALT_BYTE_SIZE)));

This makes that when the user set the property 'salt-byte-size', hashByteSize is set instead of saltByteSize

**Comment by scheuchzer** [comment]
Thanks for reporting this issue!

**Comment by llsilveira** [comment]
NP. I'm using this with your JDBCRealm for glassfish and I was trying to configure it to use 32 bytes for hash and salt. I realized though that the configuration does not matter because the password checking uses the number of bytes actually stored.

BTW, thank you to provide this and the JDBCRealm. There's not much for salted password for glassfish (what is a shame), and yours is a pretty solid one.

**Comment by scheuchzer** [comment]
Yes, hash and salt size do not affect your existing hashes. They only affect new hashes. By the way, I also updated the glassfish-jdbc-realm-salted project by now.
Yes, I was quite surprised that nobody else on this world ever wanted to use hashed password with glassfish...
